class_view_demo/class_view_demo/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('front.urls'))
]

class_view_demo/front/urls.py
from django.urls import path
from . import views


app_name = 'front'

urlpatterns = [
    path('add/', views.add_article, name='add_article'),
    path('list/', views.ArticleListView.as_view(),name='article_list'),
]

class_view_demo/front/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

class_view_demo/front/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
from django.views.generic import ListView


def add_article(request):
    articles = []
    for i in range(102):
        article = Article(title='标题：%s' % i, content='内容：%s' % i)
        articles.append(article)
    Article.objects.bulk_create(articles)
    return HttpResponse('article added successfully.')


class ArticleListView(ListView):
    model = Article
    template_name = 'front/article_list.html'
    paginate_by = 10
    context_object_name = 'articles'
    ordering = 'create_time'
    page_kwarg = 'P'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data()
        context['username'] = 'cj'
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator, page_obj)
        context.update(pagination_data)
        return context

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages
        left_has_more = False
        right_has_more = False

        if current_page <= around_count+2:
            left_pages = range(1, current_page)
        else:
            left_pages = range(current_page-around_count, current_page)
            left_has_more = True

        if current_page >= num_pages-around_count-1:
            right_pages = range(current_page+1, num_pages+1)
        else:
            right_pages = range(current_page+1, current_page+around_count+1)
            right_has_more = True
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'num_pages': num_pages,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more
        }

class_view_demo/front/templates/front/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <ul>
        {% for article in articles %}
            <li>{{ article.title }}</li>
        {% endfor %}
    </ul>
    <ul class="pagination">
{#        <li class="disabled"><a href="#">上一页</a></li>#}
{#        <li class="active"><a href="#">1</a></li>#}
{#        <li><a href="#">2</a></li>#}
{#        <li><a href="#">3</a></li>#}
{#        <li><a href="#">4</a></li>#}
{#        <li><a href="#">5</a></li>#}
{#        <li><a href="#">下一页</a></li>#}
        {# 上一页 #}
        {% if page_obj.has_previous %}
            <li><a href="{% url 'front:article_list' %}?P={{ page_obj.previous_page_number }}">上一页</a></li>
        {% else %}
            <li class="disabled"><a href="javascript:void(0)">上一页</a></li>
        {% endif %}

{#        {% for page in paginator.page_range %}#}
{#            {% if page == page_obj.number %}#}
{#                <li class="active"><a href="javascript:void(0)">{{ page }}</a></li>#}
{#            {% else %}#}
{#                <li><a href="{% url 'front:article_list' %}?P={{ page }}">{{ page }}</a></li>#}
{#            {% endif %}#}
{#        {% endfor %}#}
    
        {#左边的页码#}
        {% if left_has_more %}
            <li><a href="{% url 'front:article_list' %}?P=1">1</a></li>
            <li><a href="javascript:void(0);">...</a></li>
        {% endif %}
        {% for i in left_pages %}
            <li><a href="{% url 'front:article_list' %}?P={{ i }}">{{ i }}</a></li>
        {% endfor %}

        {#当前的页码#}
        <li class="active"><a href="javascript:void(0)">{{ current_page }}</a></li>

        {#右边的页码#}
        {% for j in right_pages %}
            <li><a href="{% url 'front:article_list' %}?P={{ j }}">{{ j }}</a></li>
        {% endfor %}
        {% if right_has_more %}
            <li><a href="javascript:void(0);">...</a></li>
            <li><a href="{% url 'front:article_list' %}?P={{ num_pages }}">{{ num_pages }}</a></li>
        {% endif %}



        {# 下一页 #}
        {% if page_obj.has_next %}
            <li><a href="{% url 'front:article_list' %}?P={{ page_obj.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="disabled"><a href="javascript:void(0)">下一页</a></li>
        {% endif %}
    </ul>
</body>
</html>